---
firewall:
  policy: deny
  allow_rules:
    ipv4:
      - name: "SSH from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '22'
      - name: "Allow k8s nodes"
        src: "192.168.88.131"
      - name: "Allow k8s nodes"
        src: "192.168.88.132"
      - name: "Allow k8s nodes"
        src: "192.168.88.133"
      - name: "Allow funnel"
        src: "10.244.0.0/16"
    ipv6:
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::"
        port: "546"
      - name: "Allow flannel virtual interface IP address"
        src: "fd09:09c5:5ecd::/48"
      - name: "Allow k8s service subnet IP address"
        src: "fdd4:6e2b:a5f9::/108"
      - name: "Allow link-local IP address"
        src: "fe80::/16"

rsyslog:
  rsyslog_client_additional_actions: |
    if ($msg contains "Attempting to mount") or
       ($msg contains "enabling forceuid mount option implicitly") or
       ($msg contains "enabling forcegid mount option implicitly") then {
        stop
    }

kubernetes_join_command_extra_opts: "--ignore-preflight-errors=Port-10250"
