---
- name: "Start OpenWebUI Docker Compose"
  community.docker.docker_compose_v2:
    project_src: /root/webui/
    state: present
  listen: "Up webui"

- name: "Start Qdrant Docker Compose"
  community.docker.docker_compose_v2:
    project_src: /root/qdrant
    state: present
  listen: "Up qdrant"
