gzip on;
gzip_comp_level 7;
gzip_min_length 1024;
gzip_vary on;
gzip_proxied any;

server {
  listen 80;
  listen [::]:80;

  server_name ss.hayaworld.home;
  return 301 https://$host:443$request_uri;
}

server {
  listen [::]:443 ssl ipv6only=on;
  listen 443 ssl;

  server_name ss.hayaworld.home;

  ssl_certificate /certs/hayaworld_cert.pem;
  ssl_certificate_key /certs/hayaworld_priv.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers HIGH:!aNULL:!MD5;

  charset UTF-8;
  root /usr/share/nginx/html;

  autoindex on;
  autoindex_exact_size off;
  autoindex_localtime on;

  add_before_body /header.html;

  location / {
  }
}
