nextcloud_nfs_server: "192.168.88.10"
nextcloud_nfs_src: "/mnt/backup/Service_Backups/nextcloud"
nextcloud_nfs_dest: "/mnt/nextcloud"

nextcloud_i915_driver_url: "{{ igpu_driver.url }}"
nextcloud_i915_driver_dest: "{{ igpu_driver.dest }}"
nextcloud_i915_driver_checksum: "{{ igpu_driver.checksum }}"

nextcloud_i915_driver_install: true

nextcloud_version: "20260409_094910"
