---
- name: "Tailscale sysctl restart"
  ansible.builtin.command:
    cmd: "sysctl -p /etc/sysctl.d/99-tailscale.conf"
  register: retval
  changed_when: retval.rc == 0
  listen: "tailscale sysctl"

- name: "Hostname Fix service Apply"
  ansible.builtin.systemd_service:
    name: fix_tailscale_name.service
    state: restarted
    enabled: true
    daemon_reload: true
  listen: "Hostname Fix service Apply"
