---
- name: Play for Open WebUI FrontEnd
  hosts: ai
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: "Common Settings"
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_install_users: true

    # https://vulkan.lunarg.com/sdk/home#linux
    - name: "Install iGPU Relational things"
      ansible.builtin.import_role:
        name: igpu
      vars:
        igpu_kernel_install: false
        igpu_vulkan_install: true
      tags:
        - igpu
        - vulkan

    - name: "Install OpenWebUI"
      ansible.builtin.import_role:
        name: openwebui
      vars:
        docker_drive_is_opt_docker: true
        docker_btrfs: true
        docker_drive_uuid: "5603a159-0211-4591-8be0-f61ab1007c60"
      tags:
        - webui

    - name: "Install BorgBackup and Configuration Backup"
      ansible.builtin.import_role:
        name: borg
      vars:
        borg_device: "/mnt/backup/Service_Backups/openwebui"
        borg_sources:
          - src: webui_open-webui
            dest: webui_open-webui
          - src: qdrant_qdrant_storage
            dest: qdrant_qdrant_storage
      tags:
        - borg

    - name: "Install Zabbix agent"
      ansible.builtin.import_tasks:
        file: tasks/zabbix-agent2.yml
      tags:
        - zabbix

    - name: "Setup Tailscale Endpoint"
      ansible.builtin.import_role:
        name: tailscale_install
      vars:
        tailscale_install_tags:
          - ai
        tailscale_install_serve: true
        tailscale_install_funnel: true
        tailscale_install_serve_https_port: 443
        tailscale_install_serve_set_path: "/"
        tailscale_install_serve_url: "http://127.0.0.1:8080"
        tailscale_install_args: "--accept-dns=true"
      tags:
        - tailscale

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram

    - name: "Enable Huge Pages"
      community.general.ini_file:
        path: "/etc/sysctl.d/99-hugepage.conf"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        state: present
        no_extra_spaces: true
        mode: "644"
      loop:
        - option: "vm.max_map_count"
          value: "262144" # 2MiB Chunk
      notify: "hugepage sysctl"
      tags:
        - zram
