---
- name: Play for Open WebUI FrontEnd
  hosts: ai
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: "Common Settings"
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_install_users: false

    - name: "Install OpenWebUI"
      ansible.builtin.import_role:
        name: openwebui
      vars:
        docker_drive_is_opt_docker: true
        docker_btrfs: true
        docker_drive_uuid: "5603a159-0211-4591-8be0-f61ab1007c60"
      tags:
        - webui

    - name: "Install BorgBackup and Configuration Backup"
      ansible.builtin.import_role:
        name: borg
      vars:
        borg_device: "/mnt/backup/Service_Backups/openwebui"
        borg_sources:
          - src: webui_open-webui
            dest: webui_open-webui
      tags:
        - borg

    - name: "Install Zabbix agent"
      ansible.builtin.import_tasks:
        file: tasks/zabbix-agent2.yml
      tags:
        - zabbix

    - name: "Install and Configure Tailscale"
      ansible.builtin.import_tasks:
        file: tasks/ai/tailscale.yml
      tags:
        - tailscale
