---
- name: Play for DNS servers
  hosts: dns
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/dns/CNAME.yml
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_add_hosts: true
        common_install_users: true
        common_network_nameserver_addresses:
          - "202.232.2.3"
          - "202.232.2.2"

    - name: "Install Applications"
      tags:
        - apps
      block:
        - name: Install Docker
          ansible.builtin.import_role:
            name: docker
          vars:
            docker_users:
              - ansible
              - hayato
          tags:
            - docker

        - name: "Setup dnsmasq"
          ansible.builtin.import_role:
            name: dns
          vars:
            dns_cname: "{{ cname }}"
          tags:
            - dns

        - name: "Setup Upstream DNS Server with pihole"
          ansible.builtin.import_role:
            name: pihole
          vars:
            pihole_install_docker: false

        - name: "Setup Kea DHCP Server"
          ansible.builtin.import_role:
            name: dhcp
          vars:
            dhcp_info: "{{ dhcp }}"
          tags:
            - dhcp

    - name: "System Configurations"
      tags:
        - config
      block:
        - name: Mount tmpfs for temporary dirs
          ansible.posix.mount:
            src: "tmpfs"
            path: "{{ item }}"
            opts: "defaults"
            fstype: tmpfs
            state: mounted
          loop:
            - "/home/ansible/.ansible"
            - "/var/cache/apt/archives"
          tags:
            - mount

        - name: "No localbind"
          community.general.ini_file:
            path: "/etc/sysctl.d/00-localbind.conf"
            option: "net.ipv4.ip_nonlocal_bind"
            value: 1
            state: present
            no_extra_spaces: true
            mode: "644"
          notify: "localbind sysctl"

        - name: Install/Config Zramswap
          ansible.builtin.import_role:
            name: zramswap
          tags:
            - zram

        - name: Setup journalctl
          ansible.builtin.import_tasks:
            file: tasks/dns/journalctl.yml

    - name: "Installing Maintenance Tools"
      tags:
        - maintenance
      block:
        - name: "Setup Tailscale Endpoint"
          ansible.builtin.import_role:
            name: tailscale_install
          vars:
            tailscale_install_tags:
              - gw
              - dns
            tailscale_install_serve: true
            tailscale_install_funnel: false
            tailscale_install_serve_https_port: 443
            tailscale_install_serve_set_path: "/"
            tailscale_install_serve_url: "http://127.0.0.1:80"
            tailscale_install_args: "--accept-dns=false"
          tags:
            - tailscale

        - name: Install Zabbix agent
          ansible.builtin.import_tasks:
            file: tasks/zabbix-agent2.yml
          tags:
            - zabbix

        - name: "Configure Rsyslog"
          ansible.builtin.import_role:
            name: rsyslog_client
          vars:
            rsyslog_client_journald_persistent: false
          tags:
            - rsyslog

        - name: APC UPS Settings
          ansible.builtin.import_role:
            name: apcupsd
          vars:
            apcupsd_role: "{{ ups.role }}"
            apcupsd_timeout: 600
          tags:
            - apc
            - ups

    - name: "Installing For qd(HW) Tools"
      when: is_hardware
      tags:
        - qd
      block:
        - name: Scrutiny collector setting
          ansible.builtin.import_role:
            name: scrutiny_collector
          vars:
            scrutiny_collector_server_id: "{{ common_hostinfo.shortname }}"
            scrutiny_collector_cron: true
          tags:
            - scrutiny

        - name: Install QDevice for NUC(Proxmox)
          ansible.builtin.import_tasks:
            file: tasks/qd/nuc_quorum_install.yml
          tags:
            - quorum
            - proxmox

        - name: Install SNMPv2
          ansible.builtin.import_tasks:
            file: tasks/qd/snmpd.yml
          vars:
            ipaddr: "{{ common_hostinfo.ipv4 }}"
          tags:
            - snmp

        - name: "Setup Tailscale Endpoint (for HW)"
          ansible.builtin.import_role:
            name: tailscale_install
          vars:
            tailscale_install_tags:
              - gw
              - dns
            tailscale_install_serve: true
            tailscale_install_funnel: false
            tailscale_install_serve_https_port: 443
            tailscale_install_serve_set_path: "/"
            tailscale_install_serve_url: "http://127.0.0.1:80"
            tailscale_install_args: "--advertise-routes=192.168.88.0/24 --advertise-exit-node --accept-dns=false"
          tags:
            - tailscale
