---
- name: Play for AI base VM
  hosts: llama
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_install_users: true

    # https://vulkan.lunarg.com/sdk/home#linux
    - name: "Install iGPU Relational things"
      ansible.builtin.import_role:
        name: igpu
      vars:
        igpu_kernel_install: false
        igpu_vulkan_install: true
      tags:
        - igpu
        - vulkan

    - name: "Install Tools"
      ansible.builtin.apt:
        pkg:
          - vim
          - lsof
          - nvtop
          - vulkan-tools
          - rsync
        state: present
        update_cache: true

    - name: "Install tika"
      ansible.builtin.import_role:
        name: tika
      vars:
        docker_drive_is_opt_docker: false
      tags:
        - tika

    - name: Create Docker Mount dir
      ansible.builtin.file:
        path: "/opt/models"
        state: directory
        owner: hayato
        group: hayato
        mode: '0755'

    - name: "Mount Skylark / Mount skylark"
      ansible.posix.mount:
        src: "UUID=8ef3f125-188b-4662-bfca-699a71a20d15"
        path: "/opt/models"
        opts: "defaults,noatime,async"
        fstype: ext4
        state: mounted

    - name: "Clone llama-swap from GitHub" # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/mostlygeek/llama-swap.git
        dest: /home/hayato/Source/llama-swap

    - name: "Setup Tailscale Endpoint"
      ansible.builtin.include_role:
        name: tailscale_install
        apply:
          tags:
            - tailscale
      tags:
        - tailscale
      vars:
        tailscale_install_tags:
          - ai
        tailscale_install_serve: true
        tailscale_install_funnel: true
        tailscale_install_serve_https_port: 443
        tailscale_install_serve_set_path: "/"
        tailscale_install_serve_url: "http://localhost:8080"
        tailscale_install_args: "--accept-dns=false"

    - name: Install Zabbix agent
      ansible.builtin.import_tasks:
        file: tasks/zabbix-agent2.yml
      tags:
        - zabbix

    - name: "Mount skylark Model Dir"
      tags:
        - skylark
      ansible.builtin.import_role:
        name: mount_skylark
      vars:
        mount_src_path: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30666333616462666433356131626538376632343632376234636535343963313432613237633136
          3365356462616436326230316634386137363135376565320a366565343332333731303938623764
          39613338393161303863616237313931633432303562666264346362663261613836646135346532
          3135356338343038310a353566323431363261303635623537363161616131393466623965346163
          34333066313333386366346563393562383864383266363630323466663831326165
        mount_dest_path: "/home/hayato/Models"
        mount_opts_additional: "ro"
        mount_uid: "{{ user | selectattr('name', 'eq', 'hayato') | map(attribute='uid') | first }}"
        mount_gid: "{{ user | selectattr('name', 'eq', 'hayato') | map(attribute='gid') | first }}"

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram

    - name: "Enable Huge Pages"
      community.general.ini_file:
        path: "/etc/sysctl.d/99-hugepage.conf"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        state: present
        no_extra_spaces: true
        mode: "644"
      loop:
        - option: "vm.max_map_count"
          value: "262144" # 2MiB Chunk
      notify: "hugepage sysctl"
      tags:
        - zram

    - name: "Configure Rsyslog"
      ansible.builtin.import_role:
        name: rsyslog_client
      tags:
        - rsyslog
