---
- name: Play for log.hayaworld.home
  hosts: log
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_pkg: "{{ apt }}"
        common_install_users: true

    - name: Prepare Graylog data dir
      tags:
        - mount
      block:
        - name: Create Graylog Mount dir
          ansible.builtin.file:
            path: "/opt/data"
            state: directory
            owner: root
            group: root
            mode: '0755'

        - name: "Mount Graylog drive"
          ansible.posix.mount:
            src: "UUID={{ graylog_drive_uuid }}"
            path: "/opt/data"
            opts: "defaults,noatime,async"
            fstype: ext4
            state: mounted

    - name: "Install and Configure Graylog"
      ansible.builtin.import_role:
        name: graylog
      vars:
        graylog_hostname: "{{ common_hostinfo.shortname }}"
      tags:
        - graylog
        - rsyslog

    - name: "Install BorgBackup and Configuration Backup"
      ansible.builtin.import_role:
        name: borg
      vars:
        borg_device: "/mnt/backup/Service_Backups/graylog"
        borg_sources:
          - src: /opt/data/mongodb
            dest: mongodb
          - src: /opt/data/graylog
            dest: graylog
          - src: /opt/data/opensearch
            dest: opensearch
      tags:
        - borg

    - name: APC UPS Settings
      ansible.builtin.import_role:
        name: apcupsd
      vars:
        apcupsd_role: "slave"
        apcupsd_timeout: 80
      tags:
        - apc
        - ups

    - name: "Setup Tailscale Endpoint"
      ansible.builtin.import_role:
        name: tailscale_install
      vars:
        tailscale_install_tags:
          - log
        tailscale_install_serve: true
        tailscale_install_funnel: false
        tailscale_install_serve_https_port: 443
        tailscale_install_serve_set_path: "/"
        tailscale_install_serve_url: "http://127.0.0.1:9000"
        tailscale_install_args: "--accept-dns=true"
      tags:
        - tailscale

    - name: Install Zabbix agent
      ansible.builtin.import_tasks:
        file: tasks/zabbix-agent2.yml
      tags:
        - zabbix

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram
