---
- name: Play for nuc02.hayaworld.home
  hosts: nuc02
  remote_user: root
  gather_facts: true

  vars_files:
    - inventories/host_vars/nuc02.yml
    - inventories/host_vars/networks.yml

  tasks:
    - name: "Common / Make directory ~/.ssh/"
      ansible.builtin.file:
        path: /.ssh/
        state: directory
        owner: root
        group: root
        mode: '0700'
      tags:
        - authorized_keys

    - name: "Common / Put authorized_keys"
      ansible.builtin.copy:
        src: templates/all/home/hayato/.ssh/authorized_keys
        dest: /.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'
      tags:
        - authorized_keys

    - name: "Get ESXi facts"
      community.vmware.vmware_host_facts:
        hostname: "nuc02.hayaworld.home"
        username: "{{ auth.username }}"
        password: "{{ auth.password }}"
        validate_certs: false
      register: result
      delegate_to: localhost

    - name: "Debug"
      ansible.builtin.debug:
        msg: "{{ result }}"
