---
- name: Play for qd.hayaworld.home
  hosts: qd
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/dns/CNAME.yml
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_pkg: "{{ apt }}"
        common_install_users: true
        common_network_nameserver_addresses:
          - "202.232.2.3"
          - "202.232.2.2"

    - name: "System Configurations"
      tags:
        - system
      block:
        - name: Mount tmpfs for temporary dirs
          ansible.posix.mount:
            src: "tmpfs"
            path: "{{ item }}"
            opts: "defaults"
            fstype: tmpfs
            state: mounted
          loop:
            - "/home/ansible/.ansible"
            - "/var/cache/apt/archives"
            - "/var/log/kea"
            - "/var/log"
          tags:
            - mount

        - name: Setup journalctl
          ansible.builtin.import_tasks:
            file: tasks/dns/journalctl.yml

        - name: Install/Config Zramswap
          ansible.builtin.import_tasks:
            file: tasks/zram.yml
          tags:
            - zram

    - name: Install QDevice for NUC(Proxmox)
      ansible.builtin.import_tasks:
        file: tasks/qd/nuc_quorum_install.yml
      tags:
        - quorum
        - proxmox

    - name: "Install Docker"
      ansible.builtin.import_role:
        name: docker
      vars:
        docker_users:
          - ansible
          - hayato
      tags:
        - docker

    - name: "Installing Services for DNS"
      tags:
        - dns
      block:
        - name: "Setup dnsmasq as resolve hayaworld.home"
          ansible.builtin.import_role:
            name: dns
          vars:
            dns_cname: "{{ cname }}"

        - name: "Setup Upstream DNS Server with pihole"
          ansible.builtin.import_role:
            name: pihole
          vars:
            pihole_install_docker: false

    - name: "DHCP Server Configurations"
      tags:
        - dhcp
      block:
        - name: "Setup Kea DHCP Server"
          ansible.builtin.import_role:
            name: dhcp
          vars:
            dhcp_info: "{{ dhcp }}"

        - name: "Set Swappiness"
          community.general.ini_file:
            path: "/etc/sysctl.d/00-localbind.conf"
            option: "net.ipv4.ip_nonlocal_bind"
            value: 1
            state: present
            no_extra_spaces: true
            mode: "644"
          notify: "localbind sysctl"

    - name: "Installing Maintenance Tools"
      tags:
        - maintenance
      block:
        - name: Install Tailscale as Exitnode/Subnet Router (for maintenance)
          ansible.builtin.import_tasks:
            file: tasks/tailscale.yml
          tags:
            - tailscale

        - name: "Setup Tailscale serve"
          ansible.builtin.import_tasks:
            file: tasks/qd/tailscale.yml
          tags:
            - tailscale

        - name: Install Zabbix agent
          ansible.builtin.import_tasks:
            file: tasks/zabbix-agent2.yml
          tags:
            - zabbix

        - name: Install SNMPv2
          ansible.builtin.import_tasks:
            file: tasks/qd/snmpd.yml
          vars:
            ipaddr: "{{ common_hostinfo.ipv4 }}"
          tags:
            - snmp

        - name: "Configure Rsyslog"
          ansible.builtin.import_role:
            name: rsyslog_client
          vars:
            rsyslog_client_journald_persistent: false
          tags:
            - rsyslog

        - name: APC UPS Settings
          ansible.builtin.import_role:
            name: apcupsd
          vars:
            apcupsd_role: "{{ ups.role }}"
            apcupsd_timeout: 600
          tags:
            - apc
            - ups

        - name: Scrutiny collector setting
          ansible.builtin.import_role:
            name: scrutiny_collector
          vars:
            scrutiny_collector_server_id: "{{ common_hostinfo.shortname }}"
            scrutiny_collector_cron: true
          tags:
            - scrutiny
