---
- name: Play for DNS servers
  hosts: rui
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/dns/CNAME.yml
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_add_hosts: false
        common_install_users: false

    - name: Mount tmpfs for temporary dirs
      ansible.posix.mount:
        src: "tmpfs"
        path: "{{ item }}"
        opts: "defaults"
        fstype: tmpfs
        state: mounted
      loop:
        - "/home/ansible/.ansible"
        - "/var/cache/apt/archives"
        - "/var/log/kea"
      tags:
        - mount

    - name: "Setup dnsmasq"
      ansible.builtin.import_role:
        name: dns
      vars:
        dns_cname: "{{ cname }}"
      tags:
        - dns

    - name: "Setup Kea DHCP Server"
      ansible.builtin.import_role:
        name: dhcp
      vars:
        dhcp_info: "{{ dhcp }}"
      tags:
        - dhcp

    - name: Setup journalctl
      ansible.builtin.import_tasks:
        file: tasks/dns/journalctl.yml

    - name: "Setup Tailscale Endpoint"
      ansible.builtin.import_role:
        name: tailscale_install
      vars:
        tailscale_install_tags:
          - dns
        tailscale_install_args: "--accept-dns=false --advertise-routes=192.168.88.100/32"
      tags:
        - tailscale

    - name: APC UPS Settings
      ansible.builtin.import_role:
        name: apcupsd
      vars:
        apcupsd_role: "slave"
        apcupsd_timeout: 60
      tags:
        - apc
        - ups

    - name: "Configure Rsyslog"
      ansible.builtin.import_role:
        name: rsyslog_client
      vars:
        rsyslog_client_journald_persistent: false
      tags:
        - rsyslog

    - name: Install Zabbix agent
      ansible.builtin.import_tasks:
        file: tasks/zabbix-agent2.yml
      tags:
        - zabbix

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram
