- name: Play for searxng web search
  hosts: searxng
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_install_users: true

    - name: Install ShortStory Store
      ansible.builtin.import_role:
        name: searxng
      vars:
        docker_drive_is_opt_docker: true
        docker_btrfs: false
        docker_drive_fstype: ext4
        docker_drive_opts: "defaults,noatime,async"
        docker_drive_uuid: "32bf2d7a-b259-4c7d-bc0d-a4bb8d7d732c"
        docker_users:
          - hayato
      tags:
        - searxng
        - search
        - searching

    - name: "Install firecrawl"
      ansible.builtin.import_role:
        name: firecrawl
      vars:
        docker_install: false
        tailscale_install: false
      tags:
        - firecrawl

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram
