---
- name: Play for skylark Datastore
  hosts: skylark
  remote_user: hayato
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  tasks:
    - name: "Common / Set Hostinfo"
      ansible.builtin.set_fact:
        common_hostinfo: "{{ network | selectattr('ipv4', 'eq', mgmt_ipv4) | first }}"
      vars:
        mgmt_ipv4: "{{ ansible_all_ipv4_addresses | select('match', '192.168.88.') | first }}"
      tags:
        - always

    - name: Scrutiny collector setting
      ansible.builtin.import_role:
        name: scrutiny_collector
      vars:
        scrutiny_collector_server_id: "{{ common_hostinfo.shortname }}"
        scrutiny_collector_cron: true
        scrutiny_collector_install_bin: "/usr/local/bin"
        scrutiny_collector_install_etc: "/usr/local/etc"
        scrutiny_collector_smartctl: "/opt/sbin/smartctl"
        scrutiny_collector_device:
          - device: /dev/sda
            type: 'sat,auto'
          - device: /dev/sdb
            type: 'sat,auto'
          - device: /dev/sdc
            type: 'sat,auto'
          - device: /dev/sdd
            type: 'sat,auto'
          - device: /dev/sde
            type: 'sat,auto'
          - device: /dev/sdf
            type: 'sat,auto'
      tags:
        - scrutiny

    - name: "Install Locales"
      ansible.builtin.apt:
        name: locales
        state: present
        update_cache: true
      notify: "locale gen for skylark"
