- name: Play for ss store servers
  hosts: ss
  remote_user: ansible
  gather_facts: true
  become: true

  vars_files:
    - host_vars/networks.yml

  handlers:
    - name: Restart handler tasks
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Common Settings
      ansible.builtin.import_role:
        name: common
      vars:
        common_firewall: "{{ firewall }}"
        common_install_users: true

    - name: Install ShortStory Store
      ansible.builtin.import_role:
        name: shortstory
      vars:
        shortstory_ipaddr: "192.168.88.120"
        docker_drive_is_opt_docker: true
        docker_btrfs: true
        docker_drive_uuid: "5603a159-0211-4591-8be0-f61ab1007c60"
        docker_users:
          - hayato
      tags:
        - ss

    - name: "Install BorgBackup and Configuration Backup"
      ansible.builtin.import_role:
        name: borg
      vars:
        borg_device: "/mnt/backup/Service_Backups/ss"
        borg_sources:
          - src: /ss/nginx/html
            dest: html
      tags:
        - borg

    - name: Install/Config Zramswap
      ansible.builtin.import_role:
        name: zramswap
      tags:
        - zram
