services:
  ollama:
    image: ollama/ollama:0.30.7
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - /home/hayato/Models:/root/Models:ro
      - /dev/hugepages:/dev/hugepages
    devices:
      - /dev/dri:/dev/dri
    environment:
      GLIBC_TUNABLES: glibc.malloc.hugetlb=1
      HUGETLB_MORECORE: yes
      OLLAMA_FLASH_ATTENTION: true
      OLLAMA_IGPU_ENABLE: true
      OLLAMA_INTEL_GPU: 1
      OLLAMA_KEEP_ALIVE: -1
      OLLAMA_KV_CACHE_TYPE: q4_0
      OLLAMA_NEW_ENGINE: 1
      OLLAMA_NEW_ESTIMATES: 1
      OLLAMA_NOPRUNE: true
      OLLAMA_NUM_PARALLEL: 1
      OLLAMA_ORIGINS: "*"
      OLLAMA_VULKAN: 1
    deploy:
      resources:
        limits:
          pids: 65535
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - SYS_ADMIN
      - IPC_LOCK
    restart: unless-stopped

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped

volumes:
  ollama:

networks:
  default:
    enable_ipv6: true
