services:
  ollama:
    image: ollama/ollama:0.30.0-rc31
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - /home/hayato/Models:/root/Models:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_ORIGINS="*"
      - OLLAMA_INTEL_GPU=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_FLASH_ATTENTION=false
      - OLLAMA_IGPU_ENABLE=true
      - OLLAMA_KEEP_ALIVE="-1"
    restart: unless-stopped

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped

volumes:
  ollama:
