---
- name: "Initialize Borgbackup"
  ansible.builtin.include_tasks:
    file: handlers/initialize_backup.yml
  listen: "Initialize Borgbackup"

- name: "Restart cron"
  ansible.builtin.systemd_service:
    name: cron.service
    state: restarted
    enabled: true
  listen: "Restart cron"
