---
- name: "Run update-grub"
  ansible.builtin.command:
    cmd: update-grub
  register: retval
  changed_when: retval.rc == 0
  listen: "Run update-grub"

- name: "Run update-initramfs"
  ansible.builtin.command:
    cmd: update-initramfs -u -k all
  register: retval
  changed_when: retval.rc == 0
  listen: "Run update-initramfs"

- name: "Restart ksmtuned"
  ansible.builtin.systemd_service:
    name: ksmtuned.service
    state: restarted
    enabled: true
  listen: "Restart ksmtuned"

- name: "KSM Cache extend for ksm service restart"
  ansible.builtin.command:
    cmd: "echo '2' > /sys/kernel/mm/ksm/run"
  register: retval
  changed_when: retval.rc == 0
  listen: "KSM cache extend"

- name: "Echo reboot notice"
  ansible.builtin.debug:
    msg: "Please Reboot Here."
  listen: "Echo reboot notice"

- name: "Restart cron"
  ansible.builtin.systemd_service:
    name: cron.service
    state: restarted
    enabled: true
  listen: "Restart cron"

- name: "Restart iscsi"
  ansible.builtin.systemd_service:
    name: iscsi
    state: restarted
    enabled: true
  listen: "Restart iscsi"

- name: "Rescan udev rules"
  ansible.builtin.command:
    cmd: "udevadm control --reload-rules"
  register: retval
  changed_when: retval.rc == 0
  listen: "Rescan udev rules"

- name: "Restart and update systemd-logind"
  ansible.builtin.systemd_service:
    name: systemd-logind
    state: restarted
    daemon_reload: true
  listen: "Restart systemd-logind"

- name: "Restart sysfsutils"
  ansible.builtin.systemd_service:
    name: sysfsutils.service
    state: restarted
    enabled: true
    daemon_reload: true
  listen: "Restart sysfsutils"
