proxmox_i915_driver_checksum: "{{ igpu_driver.checksum }}"
proxmox_i915_driver_dest: "{{ igpu_driver.dest }}"
proxmox_i915_driver_url: "{{ igpu_driver.url }}"

proxmox_ksm:
  - option: "KSM_SLEEP_MSEC"
    value: 30
  - option: "KSM_NPAGES_MAX"
    value: 1280
  - option: "KSM_THRES_COEF"
    value: 50

proxmox_zramswap_algo: lz4
proxmox_zramswap_percent: 15

proxmox_swappiness: 20

proxmox_cpu:
  governor: performance

# Use common_hostinfo.macaddress
proxmox_macaddr: "00:00:00:00:00:00"
