proxmox_i915_driver_checksum: "sha256:53a65f71c48f9f593009fad6139c7fd2d4ee76dec3b49518a185ec7a622e463b"
proxmox_i915_driver_dest: "/root/i915-sriov-dkms_2026.03.05_amd64.deb"
proxmox_i915_driver_url: https://github.com/strongtz/i915-sriov-dkms/releases/download/2026.03.05/i915-sriov-dkms_2026.03.05_amd64.deb

proxmox_ksm:
  - option: "KSM_SLEEP_MSEC"
    value: 30
  - option: "KSM_NPAGES_MAX"
    value: 1280
  - option: "KSM_THRES_COEF"
    value: 50

proxmox_zramswap_algo: lz4
proxmox_zramswap_percent: 15

proxmox_swappiness: 20

proxmox_cpu:
  governor: performance

# Use common_hostinfo.macaddress
proxmox_macaddr: "00:00:00:00:00:00"
