---
- name: Install Docker
  ansible.builtin.import_tasks:
    file: tasks/docker.yml
  tags:
    - docker

- name: Install Tailscale
  ansible.builtin.import_tasks:
    file: tasks/tailscale.yml
  tags:
    - tailscale

- name: Configure Nginx as a Container
  ansible.builtin.import_tasks:
    file: tasks/nginx.yml
  tags:
    - nginx
