---
- name: Install Docker
  ansible.builtin.import_tasks:
    file: tasks/docker.yml
  tags:
    - docker

- name: Install Hayaworld cert
  ansible.builtin.import_role:
    name: hayaworld_cert
  tags:
    - cert

- name: Configure Nginx as a Container
  ansible.builtin.import_tasks:
    file: tasks/nginx.yml
  tags:
    - nginx
