---
- name: Install Docker
  ansible.builtin.import_tasks:
    file: tasks/docker.yml
  tags:
    - docker

- name: "Setup Tailscale Endpoint"
  ansible.builtin.include_role:
    name: tailscale_install
    apply:
      tags:
        - tailscale
  vars:
    tailscale_install_tags:
      - ds
    tailscale_install_serve: true
    tailscale_install_funnel: true
    tailscale_install_serve_https_port: 443
    tailscale_install_serve_set_path: "/"
    tailscale_install_serve_url: "http://localhost:8080"
  tags:
    - tailscale

- name: Configure Nginx as a Container
  ansible.builtin.import_tasks:
    file: tasks/nginx.yml
  tags:
    - nginx
