---
- name: KSM Service Settings
  community.general.ini_file:
    path: /etc/ksmtuned.conf
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    mode: "644"
    ignore_spaces: true
    no_extra_spaces: true
  loop: "{{ proxmox_ksm }}"
  notify:
    - "KSM cache extend"
    - "Restart ksmtuned"

- name: Install/Config Zramswap
  ansible.builtin.import_role:
    name: zramswap
  vars:
    zramswap_algo: lz4
    zramswap_percent: 15
    zramswap_swappiness: 20
    zramswap_priority: 100
  tags:
    - zram
