---
- name: Restart docker
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
  listen: "Restart docker"

- name: "IPv6 Forwarding Enable"
  ansible.builtin.command:
    cmd: "sysctl -p /etc/sysctl.d/99-ipv6-forward.conf"
  register: retval
  changed_when: retval.rc == 0
  listen: "ipv6 forward sysctl"
