---
- name: "IPv6 Forwarding Enable"
  ansible.builtin.command:
    cmd: "sysctl -p /etc/sysctl.d/99-ipv6-forward.conf"
  register: retval
  changed_when: retval.rc == 0
  listen: "ipv6 forward sysctl"
