---
- name: "Chrome / Get Chrome GPG Key"
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/trusted.gpg.d/google.asc
    checksum: "sha256:54dea5f6c2a26091578cf52a999cebc6b64df478d37ad4dce96376b711e3b27c"
    mode: "0644"

- name: "Chrome / Add Chrome Repos"
  ansible.builtin.apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: "Chrome / Installing Google Chrome"
  ansible.builtin.apt:
    install_recommends: false
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
    pkg:
      - google-chrome-stable

- name: "Chrome / Mount tmpdir as Google-Chrome Cache"
  ansible.posix.mount:
    src: "tmpfs"
    path: "/home/hayato/.cache/google-chrome/Default"
    fstype: tmpfs
    state: mounted
