---
gui_install:
  chrome: true
  igpu: true
  remmina: true
  vlc: true
  wine: false
  mozc: true
  sushi: true
  firefox: false

gui_supplemental_packages:
  - ffmpeg
  - ffmpegthumbnailer

gui_additional_packages:

gui_i915_driver_url: https://github.com/strongtz/i915-sriov-dkms/releases/download/2026.05.06/i915-sriov-dkms_2026.05.06_amd64.deb
gui_i915_driver_dest: "/root/i915-sriov-dkms_2026.03.05_amd64.deb"
gui_i915_driver_checksum: "sha256:700b95ee06a511ed30b8bfb8fd9023f9ada89786e81cc889cbacc0c3607a47e9"
