---
gui_install:
  chrome: true
  igpu: true
  remmina: true
  vlc: true
  wine: false
  mozc: true
  sushi: true
  firefox: false

gui_wayland: false
gui_wayland_user: "{{ user[0].username }}"
gui_wayland_passwd: "{{ user[0].password_hashed }}"
gui_wayland_homedir: "{{ user[0].homedir }}"

gui_rdp: true

gui_supplemental_packages:
  - ffmpeg
  - ffmpegthumbnailer

gui_additional_packages:

gui_i915_driver_url: "{{ igpu_driver.url }}"
gui_i915_driver_dest: "{{ igpu_driver.dest }}"
gui_i915_driver_checksum: "{{ igpu_driver.checksum }}"
