---
- name: Install Docker
  ansible.builtin.include_role:
    name: docker
  vars:
    docker_drive_is_opt_docker: true
    docker_users:
      - hayato

- name: "Configure Ollama"
  tags:
    - set
  block:
    - name: "Install and Configure Ollama"
      block:
        - name: "Mkdir for Ollama docker-compose"
          ansible.builtin.file:
            path: "/home/hayato/ollama"
            state: directory
            owner: hayato
            group: hayato
            mode: '0755'

        - name: "Put Ollama docker-compose"
          ansible.builtin.copy:
            src: "templates/home/hayato/ollama/docker-compose.yml"
            dest: "/home/hayato/ollama/docker-compose.yml"
            owner: hayato
            group: hayato
            mode: '0644'
          notify: "Up ollama"
