---
- name: "Set Packet forwarding"
  when: "'advertise-routes' in tailscale_install_args"
  community.general.ini_file:
    path: "/etc/sysctl.d/99-tailscale.conf"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: false
    mode: "644"
  notify: "tailscale sysctl"
  loop:
    - option: "net.ipv4.ip_forward"
      value: "1"
    - option: "net.ipv6.conf.all.forwarding"
      value: "1"

- name: "Funnel usage check"
  block:
    - name: "Add tailscale funnel tag since this node will use tailscale funnel (Yes)"
      ansible.builtin.set_fact:
        tailscale_real_tags: "{{ tailscale_install_tags + ['funnel'] }}"
      when: tailscale_install_funnel

    - name: "This node don't use tailscale funnel"
      ansible.builtin.set_fact:
        tailscale_real_tags: "{{ tailscale_install_tags }}"
      when: not tailscale_install_funnel

- name: "Setup Tailscale Endpoint for console"
  when: not ansible_check_mode
  ansible.builtin.import_role:
    name: artis3n.tailscale.machine
  vars:
    tailscale_authkey: "{{ tailscale_install_client_secret }}"
    tailscale_args: "{{ tailscale_install_args }}"
    tailscale_oauth_ephemeral: false
    tailscale_tags: "{{ tailscale_real_tags }}"

- name: "Rename when this node's name doesn't the same of hostname"
  block:
    # tailscale_serve_retval == 0 when not configured
    - name: "Check this machine's node name"
      ansible.builtin.shell:
        cmd: |
            set -o pipefail
            tailscale whoami | grep 'Name' | awk -F':' '{print $2}' | tr -d ' '
        executable: /bin/bash
      register: tailscale_nodename_retval
      changed_when: false
      failed_when: false

    - name: "Fix this machine's node name"
      ansible.builtin.command:
        cmd: >
          tailscale set --hostname "{{ tailscale_shortname }}"
      register: retval
      changed_when: retval.rc == 0
      when:
        - tailscale_nodename_retval.stdout != (tailscale_shortname ~ "." ~ tailscale_domain)

- name: "Setup Tailscale Serve"
  when:
    - tailscale_install_serve
    - not ansible_check_mode
  block:
    # tailscale_serve_retval == 0 when not configured
    - name: "Check Tailscale serve configured"
      ansible.builtin.shell:
        cmd: |
            set -o pipefail
            tailscale serve status | grep 'No serve config'
        executable: /bin/bash
      register: tailscale_serve_retval
      changed_when: false
      failed_when: false

    # This node doesn't need to reveal WebUI to the Internet.
    - name: "Set Tailscale serve"
      ansible.builtin.command:
        cmd: >
          tailscale serve --bg
            --https={{ tailscale_install_serve_https_port }}
            --set-path={{ tailscale_install_serve_set_path }}
            {{ tailscale_install_serve_url }}
      register: retval
      changed_when: retval.rc == 0
      when:
        - tailscale_serve_retval.rc == 0

- name: "Setup Tailscale Funnel"
  when:
    - tailscale_install_serve
    - tailscale_install_funnel
    - not ansible_check_mode
  block:
    # tailscale_funnel_retval.rc == 0 when not configured
    - name: "Check Tailscale funnel configured"
      ansible.builtin.shell:
        cmd: |
            set -o pipefail
            tailscale funnel status | grep 'tailnet only'
        executable: /bin/bash
      register: tailscale_funnel_retval
      changed_when: false
      failed_when: false

    - name: "Run Tailscale funnel"
      when:
        - tailscale_funnel_retval.rc == 0
      ansible.builtin.command:
        cmd: |
          tailscale funnel --bg --https={{ tailscale_install_funnel_external_port }} {{ tailscale_install_serve_url }}
      register: retval
      changed_when: retval.rc == 0

- name: "Tailscale Firewall accept"
  community.general.ufw:
    rule: allow
    interface_in: tailscale0
    proto: any

- name: "Put hostname fix scripts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.perm }}"
  loop:
    - src: "roles/tailscale_install/templates/etc/systemd/system/fix_tailscale_name.sh"
      dest: "/etc/systemd/system/fix_tailscale_name.sh"
      perm: "0755"
    - src: "roles/tailscale_install/templates/etc/systemd/system/fix_tailscale_name.service"
      dest: "/etc/systemd/system/fix_tailscale_name.service"
      perm: "0644"
  notify: "Hostname Fix service Apply"
