---
- name: Install Docker
  ansible.builtin.import_role:
    name: docker

- name: "Mkdir for OpenWebUI docker-compose"
  ansible.builtin.file:
    path: "/root/webui"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Put OpenWebUI docker-compose"
  ansible.builtin.copy:
    src: "templates/root/webui/docker-compose.yml"
    dest: "/root/webui/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
  notify: "Up webui"

- name: "Setup Tailscale Endpoint"
  ansible.builtin.include_role:
    name: tailscale_install
    apply:
      tags:
        - tailscale
  tags:
    - tailscale
