---
- name: Install Docker
  ansible.builtin.include_role:
    name: docker
  tags:
    - docker

- name: "Setup Tailscale Endpoint"
  ansible.builtin.include_role:
    name: tailscale_install
    apply:
      tags:
        - tailscale
  vars:
    tailscale_install_tags:
      - ds
      - funnel
    tailscale_install_serve: true
    tailscale_install_funnel: true
    tailscale_install_serve_https_port: 443
    tailscale_install_serve_set_path: "/"
    tailscale_install_serve_url: "http://127.0.0.1:8080"
    tailscale_install_args: "--accept-dns=true"
  tags:
    - tailscale

- name: "Install NocoDB"
  tags:
    - config
  block:
    - name: "Create docker compose dir"
      ansible.builtin.file:
        path: "/root/nocodb"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Copy configuration files"
      ansible.builtin.template:
        src: "templates/{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - src: "root/nocodb/docker-compose.yml.j2"
          dest: "/root/nocodb/docker-compose.yml"
      notify:
        - "Restart NocoDB"

- name: "Install BorgBackup and Configuration Backup"
  ansible.builtin.import_role:
    name: borg
  vars:
    borg_device: "/mnt/backup/Service_Backups/nocodb"
    borg_sources:
      - src: /var/lib/docker/volumes/nocodb_nocodb_data
        dest: nocodb_nocodb_data
      - src: /var/lib/docker/volumes/nocodb_postgres_data
        dest: nocodb_postgres_data
      - src: /var/lib/docker/volumes/nocodb_redis_data
        dest: nocodb_redis_data
    borg_hour: "*/12"
    borg_minute: "30"
    borg_keep_hourly: 10
    borg_keep_daily: 10
    borg_keep_weekly: 8
    borg_keep_monthly: 8
  tags:
    - borg
