---
- name: "Install Docker"
  when: docker_install
  ansible.builtin.import_role:
    name: docker
  vars:
    docker_users:
      - root

- name: "Create Kea-DHCP config dir"
  ansible.builtin.file:
    path: "/root/kea"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Copy configuration files"
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - src: "root/kea/kea-dhcp4.conf.j2"
      dest: "/root/kea/kea-dhcp4.conf"
    - src: "root/kea/docker-compose.yml.j2"
      dest: "/root/kea/docker-compose.yml"
  notify:
    - "Restart kea"
