---
- name: "GPU / Install Vulkan Prerequirements"
  ansible.builtin.apt:
    pkg:
      - libvulkan-dev
      - libvulkan1
      - mesa-vulkan-drivers
      - spirv-tools
      - vulkan-tools
      - vulkan-validationlayers
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
