# FROM: https://docs.affine.pro/self-host-affine/references/docker-compose-yml
name: affine
services:
  affine:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_server
    ports:
      - '3000:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      - affine_storage:/root/.affine/storage
      - ./config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://{{ affine_db_user }}@postgres:5432/{{ affine_db_name }}
      - AFFINE_INDEXER_ENABLED=true
      - AFFINE_INDEXER_SEARCH_ENDPOINT=http://indexer:9308
      - AFFINE_SERVER_EXTERNAL_URL=https://{{ affine_external_fqdn }}:3000
      - AFFINE_FEATURES_EARLY_ACCESS=true
      - AFFINE_ENV=production
    restart: unless-stopped
    networks:
      - backend
      - default

  affine_migration:
    image: ghcr.io/toeverything/affine:stable
    container_name: affine_migration_job
    volumes:
      - affine_storage:/root/.affine/storage
      - ./config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://{{ affine_db_user }}@postgres:5432/{{ affine_db_name }}
      - AFFINE_INDEXER_ENABLED=true
      - AFFINE_INDEXER_SEARCH_ENDPOINT=http://indexer:9308
      - AFFINE_FEATURES_EARLY_ACCESS=true
      - AFFINE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - default

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: affine_postgres
    volumes:
      - postgress:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "{{ affine_db_user }}"
      POSTGRES_DB: "{{ affine_db_name }}"
      POSTGRES_DB_PASSWORD: "{{ affine_db_password }}"
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '{{ affine_db_user }}', '-d', 'affine']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

  indexer:
    image: manticoresearch/manticore:${MANTICORE_VERSION:-10.1.0}
    container_name: affine_indexer
    volumes:
      - manticore:/var/lib/manticore
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        ['CMD', 'wget', '-O-', 'http://127.0.0.1:9308']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
      - default

volumes:
  postgress:
  affine_storage:
  manticore:

networks:
  default:
    enable_ipv6: true
  backend:
    driver: bridge
    enable_ipv6: true
