---
- name: "Install"
  notify: "Up firecrawl container"
  block:
    - name: "Mkdir for firecrawl"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "/root/firecrawl"

    - name: "Git Checkout"
      ansible.builtin.git:
        repo: 'https://github.com/firecrawl/firecrawl.git'
        dest: /root/firecrawl
        version: "{{ firecrawl_version }}"

    - name: "Put Configurations"
      ansible.builtin.template:
        src: "templates/root/firecrawl/dotenv.j2"
        dest: "/root/firecrawl/.env"
        owner: root
        group: root
        mode: '0644'
