---
- name: Install Dir mkdir(/opt/bin/)
  ansible.builtin.file:
    path: "/opt/bin"
    state: directory
    mode: '0755'
  when: scrutiny_collector_install_bin == "/opt/bin"

- name: Install Dir mkdir(/opt/etc/)
  ansible.builtin.file:
    path: "/opt/etc"
    state: directory
    mode: '0755'
  when: scrutiny_collector_install_etc == "/opt/etc"

- name: "Download scrutiny-collector"
  ansible.builtin.get_url:
    url: "https://github.com/AnalogJ/scrutiny/releases/download/v0.9.2/scrutiny-collector-metrics-linux-amd64"
    dest: "{{ scrutiny_collector_install_bin }}/scrutiny-collector"
    checksum: "sha256:a8f0c8efe23afbae07957fe7ebd29ed6b3aecdf40bc00cc300c042b77b80c851"
    owner: root
    group: root
    mode: "0755"

- name: "Copy scrutiny.yml"
  ansible.builtin.template:
    src: "templates/collector.yaml.j2"
    dest: "{{ scrutiny_collector_install_etc }}/collector.yaml"
    owner: "root"
    group: "root"
    mode: '0644'

- name: "Install smartmontools"
  when: scrutiny_collector_install_smartmontools
  ansible.builtin.apt:
    name: "smartmontools"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify: "Smartmon initial installed"

- name: "Update DriveDB forcely"
  ansible.builtin.import_tasks:
    file: roles/scrutiny_collector/tasks/update_drivedb.yml
  when: scrutiny_collector_install_drivedb

- name: "Install cron"
  ansible.builtin.apt:
    name: "cron"
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: "Set crontab"
  ansible.builtin.cron:
    name: "Scrutiny Collector"
    minute: "*/2"
    job: "{{ scrutiny_collector_install_bin }}/scrutiny-collector run --config {{ scrutiny_collector_install_etc }}/collector.yaml > /dev/null 2>&1"
    cron_file: scrutiny-collector
    user: root
  when: scrutiny_collector_cron
  notify: "Restart cron"
