---
- name: "Common / Make directory for put hayaworld certs"
  ansible.builtin.file:
    path: "/usr/local/share/ca-certificates"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Common / Put hayaworld root CA certs"
  ansible.builtin.copy:
    src: "templates/usr/local/share/ca-certificates/ca.crt"
    dest: "/usr/local/share/ca-certificates/ca.crt"
    owner: root
    group: root
    mode: '0644'
  notify: "update-ca-certificates"
