---
- name: "Common / Apply netplan config (qd.hayaworld.home)"
  ansible.builtin.import_role:
    name: mrlesmithjr.netplan
  any_errors_fatal: true
  notify: "Reconfigure netplan"
  vars:
    netplan_enabled: true
    netplan_renderer: networkd
    netplan_configuration: "{{ {'network': {'ethernets': (common_network_config | from_json)}} }}"
    common_network_config: |
      {
        "{{ common_network_interface }}": {
          "addresses": [
            "{{ common_network_ipv4 }}/{{ common_network_subnetmask }}"
          ],
          "nameservers": {
            "addresses": {{ common_network_nameserver_addresses | to_json }},
            "search": {{ common_network_search | to_json }}
          },
          "routes": {{ common_network_routes | to_json }},
          "mtu": "{{ common_network_mtu }}"
        }
      }
