---
- name: Restart zramswap
  ansible.builtin.systemd_service:
    name: zramswap
    state: restarted
  listen: "Restart zramswap"

- name: "Swappiness setting for nuc sysctl restart"
  ansible.builtin.command:
    cmd: "sysctl -p /etc/sysctl.d/99-swappiness.conf"
  register: retval
  changed_when: retval.rc == 0
  listen: "swappiness sysctl"
