---
- name: Install Docker
  ansible.builtin.include_role:
    name: docker
  vars:
    docker_drive_is_opt_docker: true
    docker_users:
      - hayato

- name: "Configure llama-swap"
  tags:
    - set
  block:
    - name: "Install and Configure Ollama"
      block:
        - name: "Mkdir for Ollama docker-compose"
          ansible.builtin.file:
            path: "/home/hayato/llama"
            state: directory
            owner: hayato
            group: hayato
            mode: '0755'

        - name: "Put Ollama docker-compose"
          ansible.builtin.copy:
            src: "templates/home/hayato/llama/docker-compose.yml"
            dest: "/home/hayato/llama/docker-compose.yml"
            owner: hayato
            group: hayato
            mode: '0644'
          notify: "Up llama"

- name: "Setup Tailscale Endpoint"
  ansible.builtin.include_role:
    name: tailscale_install
    apply:
      tags:
        - tailscale
  tags:
    - tailscale
