services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama.hayaworld.home:11434
      - AIOHTTP_CLIENT_TIMEOUT=''
      - AIOHTTP_CLIENT_TIMEOUT_MODEL_LIST=''
    restart: unless-stopped

volumes:
  open-webui:
