services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    env_file:
      - environment.txt
    environment:
#      ENABLE_PERSISTENT_CONFIG: false
#      RESET_CONFIG_ON_START: true
      TITLE_GENERATION_PROMPT_TEMPLATE:  |2
        ### Task:
        Summarize this chat in about 20 characters in Japanese, without emojis.

        ### Guidelines:
        - Consider the content of the chat so that it can be distinguished from other chats.
        - DON'T USE emojis, quotation marks or special formatting.
        - Write the title in Japanese.

        ### Output:
        JSON format={ "title"="your concise title here" }

        ### Example:
        JSON format={ "title"="タイトルの例 できるだけ詳しく" }

        ### Chat History:
        <chat_history>
          {{MESSAGES:END:8}}
        </chat_history>
      TAGS_GENERATION_PROMPT_TEMPLATE: |2
        ### Task:
        Generate 1-10 broad tags categorizing the main themes of the chat history, along with 1-10 more specific subtopic tags.

        ### Guidelines:
        - Start with high-level domains (e.g., Science, Technology, Philosophy, Arts, Politics, Business, Health, Sports, Entertainment, Education)
        - Consider including relevant subfields/subdomains if they are strongly represented throughout the conversation
        - If content is too short (less than 3 messages) or too diverse, use only ["General"]
        - Use English only
        - Prioritize accuracy over specificity

        ### Output:
        JSON format={ "tags"=["tag1", "tag2", "tag3"] }

        ### Chat History:
        <chat_history>
          {{MESSAGES:END:6}}
        </chat_history>
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: 65535
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

volumes:
  open-webui:

networks:
  default:
    enable_ipv6: true
