---
- name: Prepare Docker data dir
  when: docker_drive_is_opt_docker
  tags:
    - mount
  block:
    - name: Create Docker Mount dir
      ansible.builtin.file:
        path: "/opt/docker"
        state: directory
        owner: root
        group: root
        mode: '0710'

    - name: "Mount Docker drive"
      ansible.posix.mount:
        src: "UUID={{ docker_drive_uuid }}"
        path: "/opt/docker"
        opts: "defaults,compress=zstd:1"
        fstype: btrfs
        state: mounted

    - name: Create Docker Mount dir
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0710'
      loop:
        - "/opt/docker"
        - "/opt/docker/docker"
        - "/opt/docker/containerd"

    - name: "Make symlink from Docker drive"
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        state: link
      loop:
        - src: "/opt/docker/docker"
          dest: "/var/lib/docker"
        - src: "/opt/docker/containerd"
          dest: "/var/lib/containerd"

- name: Configuration Dir mkdir
  ansible.builtin.file:
    path: /etc/docker/
    state: directory
    owner: root
    group: root
    mode: '0755'

# geerlingguy.docker : Ensure handlers are notified immediately to update the apt cache.
# 初回インストール実行時、上記handlerが走るがこれは
# geerlingguy.dockerの仕様(handlerをflushしている)でありplaybookを再度実行する必要がある
# See also:
# https://github.com/geerlingguy/ansible-role-docker/blob/30ba30832134ac03714bb1813ded1560b8478563/tasks/setup-Debian.yml#L42
- name: "Define Docker configs"
  ansible.builtin.template:
    src: "templates/etc/docker/daemon.json.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: "Restart docker"
  when: docker_config is defined

- name: Install Docker(ce)
  ansible.builtin.include_role:
    name: geerlingguy.docker

- name: "Disable CoW if btrfs"
  when: docker_btrfs and docker_drive_is_opt_docker
  ansible.builtin.command:
    cmd: "chattr +C /opt/docker"
  register: retval
  changed_when: retval.rc == 0

- name: "Set IPv6 Routing"
  community.general.ini_file:
    path: "/etc/sysctl.d/99-ipv6-forward.conf"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    no_extra_spaces: true
    mode: "644"
  notify: "ipv6 forward sysctl"
  loop:
    - option: "net.ipv6.conf.all.forwarding"
      value: 1
    - option: "net.ipv6.conf.all.accept_ra"
      value: 2
    - option: "net.bridge.bridge-nf-call-ip6tables"
      value: 1
    - option: "net.bridge.bridge-nf-call-iptables"
      value: 1
