---
firewall:
  policy: deny
  allow_rules:
    ipv4:
      - name: "SSH from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '22'
      - name: "Zabbix from Zabbix-server"
        proto: "tcp"
        src: "192.168.88.106/24"
        port: "10050"
      - name: "Open-WebUI from service line"
        proto: "tcp"
        src: "192.168.88.0/24"
        port: '8080'
    ipv6:
      - name: "DHCPv6 Client from service line"
        proto: "udp"
        src: "::"
        port: "546"

docker_config:
  ipv6: true
  ip6tables: true
  userland-proxy: false
  dns:
    - 100.100.100.100
  fixed-cidr-v6: "fd63:e64d:811c::1/64"
  bip: "172.18.6.1/24"
