---
is_hardware: false

ups:
  role: slave

rui_info: "{{ network | selectattr('shortname', 'eq', 'rui') | first }}"
qd_info: "{{ network | selectattr('shortname', 'eq', 'qd') | first }}"

dhcp:
  me:
    name: "rui"
    ipaddr: "{{ rui_info.ipv4 }}"
  search_domain: "hayaworld.home"
  lib_base: "/usr/lib/x86_64-linux-gnu/kea/hooks"
  peer4:
    - name: "qd"
      url: "http://{{ qd_info.ipv4 }}:8080/"
      role: "primary"
      auto-failover: true
    - name: "rui"
      url: "http://{{ rui_info.ipv4 }}:8080/"
      role: "standby"
      auto-failover: true
  peer6:
    - name: "qd"
      url: "http://{{ qd_info.ipv4 }}:8081/"
      role: "primary"
      auto-failover: true
    - name: "rui"
      url: "http://{{ rui_info.ipv4 }}:8081/"
      role: "standby"
      auto-failover: true
  ipv4:
    subnet: "192.168.88.0/24"
    pool: "192.168.88.21-192.168.88.99"
    ttl: "0xf0"
    gw: "{{ subnet.gw4 }}"
    dns: "{{ qd_info.ipv4 }},{{ rui_info.ipv4 }}"
    lease_db: "/var/lib/kea/kea-leases4.csv"

docker_drive_is_opt_docker: false
docker_btrfs: true
docker_config:
  ipv6: true
  ip6tables: true
  userland-proxy: false
  dns:
    - 202.232.2.3
    - 202.232.2.2
  fixed-cidr-v6: "fd56:1011:9fca::/64"
  bip: "172.18.8.1/24"
  log-driver: "syslog"
  log-opts:
    syslog-address: "unixgram:///dev/log"
    tag: "{% raw %}{{.Name}}{% endraw %}"
    syslog-format: "rfc3164"
