services:
  qdrant:
    image: qdrant/qdrant:v1.18
    container_name: qdrant
    ports:
      - "6333:6333"
    env_file:
      - environment.txt
    volumes:
      - qdrant_storage:/qdrant/storage
      - /root/qdrant/config.yaml:/qdrant/config/config.yaml:ro
      - /dev/hugepages:/dev/hugepages
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

volumes:
  qdrant_storage:

networks:
  default:
    enable_ipv6: true
