---
- name: "Install and config zram-tools"
  block:
    - name: "Install zram-tools"
      ansible.builtin.apt:
        name: "zram-tools"
        state: present
        update_cache: true

    - name: "Setting zram configurations"
      ansible.builtin.template:
        src: templates/etc/default/zramswap.j2
        dest: /etc/default/zramswap
        owner: root
        group: root
        mode: '0644'
      notify: "Restart zramswap"

- name: "Set Swappiness"
  community.general.ini_file:
    path: "/etc/sysctl.d/99-swappiness.conf"
    option: "vm.swappiness"
    value: "{{ zramswap_swappiness }}"
    state: present
    no_extra_spaces: true
    mode: "644"
  notify: "swappiness sysctl"
