services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:unified-vulkan
    container_name: llama-swap
    ports:
      - "80:8080"
    volumes:
      - models:/models
      - ./config.yaml:/etc/llama-swap/config/config.yaml:ro
      - /home/hayato/Models:/skylark/Models:ro
      - /dev/hugepages:/dev/hugepages
    tmpfs:
      - /root/.cache
    devices:
      - /dev/dri:/dev/dri
    environment:
      GLIBC_TUNABLES: glibc.malloc.hugetlb=1
      HUGETLB_MORECORE: yes
    deploy:
      resources:
        limits:
          pids: 65535
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    cap_add:
      - SYS_ADMIN
      - IPC_LOCK
    restart: unless-stopped

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - 9998:9998
    restart: unless-stopped

volumes:
  models:

networks:
  default:
    enable_ipv6: true
