---
- name: "Install Docker"
  ansible.builtin.import_role:
    name: docker

- name: "Create Dirs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "/root/pihole"
    - "/root/pihole/etc-dnsmasq.d"
    - "/root/pihole/etc-pihole"

- name: "Copy configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - src: "templates/root/pihole/docker-compose.yml.j2"
      dest: "/root/pihole/docker-compose.yml"
  notify: "Up pihole"
