*       soft    nofile  unlimited
*       hard    nofile  unlimited
root    soft    nofile  unlimited
root    hard    nofile  unlimited
*       soft    memlock unlimited
*       hard    memlock unlimited
